openapi: 3.0.0
info:
  title: Unit Servise API
  description: This is TEST API for my service
  version: 0.0.1
servers:
- url: http://localhost:8181/
  description: "Optional server description, e.g. Internal staging server for testing"
tags:
- name: unit
  description: Unit info
- name: wargears
  description: Equipment info
paths:
  /unit:
    get:
      tags:
      - unit
      summary: Returns a list of available units.
      description: Return JSON array of info available units.
      responses:
        "200":
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Unit'
                x-content-type: application/json
    post:
      tags:
      - unit
      summary: Add new unit.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EditUnit'
        required: true
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                type: string
                description: ID unit
                example: c01d7cf6-ec3f-47f0-9556-a5d6e9009a43
                x-content-type: application/json
  /unit/{unitId}:
    get:
      tags:
      - unit
      summary: Returns a unit by ID.
      parameters:
      - name: unitId
        in: path
        description: ID unit
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: c01d7cf6-ec3f-47f0-9556-a5d6e9009a43
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unit'
    put:
      tags:
      - unit
      summary: Edit unit by ID.
      parameters:
      - name: unitId
        in: path
        description: ID unit
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: c01d7cf6-ec3f-47f0-9556-a5d6e9009a43
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EditUnit'
        required: true
      responses:
        "201":
          description: Update
          content:
            application/json:
              schema:
                type: string
                description: ID unit
                example: c01d7cf6-ec3f-47f0-9556-a5d6e9009a43
                x-content-type: application/json
    delete:
      tags:
      - unit
      summary: Delete unit by ID.
      parameters:
      - name: unitId
        in: path
        description: ID unit
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: c01d7cf6-ec3f-47f0-9556-a5d6e9009a43
      responses:
        "201":
          description: Delete
          content:
            application/json:
              schema:
                type: string
                description: ID unit
                example: c01d7cf6-ec3f-47f0-9556-a5d6e9009a43
                x-content-type: application/json
  /equipment:
    get:
      tags:
      - wargears
      summary: Returns a list of available equipment.
      description: Return JSON array of info available equipments.
      responses:
        "200":
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Equipment'
                x-content-type: application/json
    post:
      tags:
      - wargears
      summary: Add new equipment.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EditEquipment'
        required: true
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                type: string
                description: ID Equipment
                example: c01d7cf6-ec3f-47f0-9556-a5d6e9009a43
                x-content-type: application/json
  /equipment/{equipmentId}:
    get:
      tags:
      - wargears
      summary: Returns a equipment by ID.
      parameters:
      - name: equipmentId
        in: path
        description: ID Equipment
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: c01d7cf6-ec3f-47f0-9556-a5d6e9009a43
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Equipment'
    put:
      tags:
      - wargears
      summary: Edit equipment by ID.
      parameters:
      - name: equipmentId
        in: path
        description: ID Equipment
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: c01d7cf6-ec3f-47f0-9556-a5d6e9009a43
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EditEquipment'
        required: true
      responses:
        "201":
          description: Update
          content:
            application/json:
              schema:
                type: string
                description: ID Equipment
                example: c01d7cf6-ec3f-47f0-9556-a5d6e9009a43
                x-content-type: application/json
    delete:
      tags:
      - wargears
      summary: Delete equipment by ID.
      parameters:
      - name: equipmentId
        in: path
        description: ID Equipment
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: c01d7cf6-ec3f-47f0-9556-a5d6e9009a43
      responses:
        "201":
          description: Delete
          content:
            application/json:
              schema:
                type: string
                description: ID Equipment
                example: c01d7cf6-ec3f-47f0-9556-a5d6e9009a43
                x-content-type: application/json
components:
  schemas:
    Unit:
      required:
      - additionalRule
      - bs
      - forceName
      - fs
      - hp
      - id
      - initiative
      - name
      properties:
        id:
          type: string
          description: ID unit
          example: c01d7cf6-ec3f-47f0-9556-a5d6e9009a43
        name:
          type: string
          description: FULL NAME unit
          example: Gregiory W. Morris
        forceName:
          type: string
          description: force name unit
          example: SPECIAL FORCES AIRBORNE
        hp:
          type: integer
          description: count heals point unit
          example: 4
        initiative:
          type: integer
          description: initiative unit
          example: 8
        bs:
          type: integer
          description: ability to shoot unit
          example: 1
        fs:
          type: integer
          description: ability to fight unit
          example: 1
        additionalRule:
          type: string
          description: Additionat ability soldes
          example: When Morris move into hand to hand combat his roll is at +2.
      example:
        bs: 1
        additionalRule: When Morris move into hand to hand combat his roll is at +2.
        initiative: 8
        forceName: SPECIAL FORCES AIRBORNE
        name: Gregiory W. Morris
        hp: 4
        id: c01d7cf6-ec3f-47f0-9556-a5d6e9009a43
        fs: 1
    EditUnit:
      required:
      - additionalRule
      - bs
      - forceName
      - fs
      - hp
      - initiative
      - name
      properties:
        name:
          type: string
          description: FULL NAME unit
          example: Gregiory W. Morris
        forceName:
          type: string
          description: force name unit
          example: SPECIAL FORCES AIRBORNE
        hp:
          type: integer
          description: count heals point unit
          example: 4
        initiative:
          type: integer
          description: initiative unit
          example: 8
        bs:
          type: integer
          description: ability to shoot unit
          example: 1
        fs:
          type: integer
          description: ability to fight unit
          example: 1
        additionalRule:
          type: string
          description: Additionat ability soldes
          example: When Morris move into hand to hand combat his roll is at +2.
    Equipment:
      required:
      - ammo
      - cost
      - id
      - limitOnTeam
      - limitOnUnit
      - name
      - rule
      - soldarRole
      properties:
        id:
          type: string
          description: ID equipment
          example: c01d7cf6-ec3f-47f0-9556-a5d6e9009a43
        name:
          type: string
          description: FULL NAME equipment
          example: M203 (Grenade Launcher)
        limitOnUnit:
          type: integer
          description: limit equipment on one unit. -1 - unlimit
          example: 1
        limitOnTeam:
          type: integer
          description: limit equipment on one team. -1 - unlimit
          example: 1
        soldarRole:
          type: string
          description: The role of a soldier available when selecting ammunition.
          example: Grenader
        rule:
          type: string
          description: game rule equipment
          example: "2 orders: The under barrel grenade launcher deals 1 wound to all\
            \ models in its AoE. The target must be in LoS and does not have to be\
            \ a model. No max range to this tossed weapon."
        ammo:
          type: integer
          description: limit equipment on game. -1 - unlimit
          example: 2
        cost:
          type: integer
          description: cost equipment in game points
          example: 3
      example:
        soldarRole: Grenader
        ammo: 2
        cost: 3
        limitOnTeam: 1
        name: M203 (Grenade Launcher)
        rule: "2 orders: The under barrel grenade launcher deals 1 wound to all models\
          \ in its AoE. The target must be in LoS and does not have to be a model.\
          \ No max range to this tossed weapon."
        id: c01d7cf6-ec3f-47f0-9556-a5d6e9009a43
        limitOnUnit: 1
    EditEquipment:
      required:
      - ammo
      - cost
      - limitOnTeam
      - limitOnUnit
      - name
      - rule
      - soldarRole
      properties:
        name:
          type: string
          description: FULL NAME equipment
          example: M203 (Grenade Launcher)
        limitOnUnit:
          type: integer
          description: limit equipment on one unit. -1 - unlimit
          example: 1
        limitOnTeam:
          type: integer
          description: limit equipment on one team. -1 - unlimit
          example: 1
        soldarRole:
          type: string
          description: The role of a soldier available when selecting ammunition.
          example: Grenader
        rule:
          type: string
          description: game rule equipment
          example: "2 orders: The under barrel grenade launcher deals 1 wound to all\
            \ models in its AoE. The target must be in LoS and does not have to be\
            \ a model. No max range to this tossed weapon."
        ammo:
          type: integer
          description: limit equipment on game. -1 - unlimit
          example: 2
        cost:
          type: integer
          description: cost equipment in game points
          example: 3
