/*
 * Unit Servise API
 *
 * This is TEST API for my service
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package Swagger

import (
	"fmt"
	"github.com/gorilla/mux"
	log "github.com/sirupsen/logrus"
	"io"
	"net/http"
	. "UnitService/pkg/Unit/app"
)

func UnitGet(w http.ResponseWriter, r *http.Request) {
	s := " [ "
	s += " { "
	s += "	\"id\": \"c01d7cf6-ec3f-47f0-9556-a5d6e9009a43\", "
	s += "	\"name\": \"Gregiory W. Morris\", "
	s += "	\"forceName\": \"SPECIAL FORCES AIRBORNE\", "
	s += "	\"hp\": 4, "
	s += "	\"initiative\": 8, "
	s += "	\"bs\": 1, "
	s += "	\"fs\": 1, "
	s += "	\"additionalRule\": \"When Morris move into hand to hand combat his roll is at +2.\" "
	s += " } "
	s += " ] "

	fmt.Fprintf(w,s)

	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}

func UnitPost(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}

func UnitUnitIdDelete(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}

func UnitUnitIdGet(w http.ResponseWriter, r *http.Request) {
	vars := mux.Vars(r)
	id := vars["unitId"]

	b, err := GetJSONUnitById(id)

	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	JSONResponse(w, b)
}

func UnitUnitIdPut(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}

func JSONResponse(w http.ResponseWriter, json []byte) {
	w.Header().Set("Content-Type","application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
	_, err := io.WriteString(w, string(json))
	if err != nil {
		log.WithField("err", err).Error("write response error")
	}
}