/*
 * Unit Servise API
 *
 * This is TEST API for my service
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package Swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/",
		Index,
	},

	Route{
		"UnitGet",
		strings.ToUpper("Get"),
		"/unit",
		UnitGet,
	},

	Route{
		"UnitPost",
		strings.ToUpper("Post"),
		"/unit",
		UnitPost,
	},

	Route{
		"UnitUnitIdDelete",
		strings.ToUpper("Delete"),
		"/unit/{unitId}",
		UnitUnitIdDelete,
	},

	Route{
		"UnitUnitIdGet",
		strings.ToUpper("Get"),
		"/unit/{unitId}",
		UnitUnitIdGet,
	},

	Route{
		"UnitUnitIdPut",
		strings.ToUpper("Put"),
		"/unit/{unitId}",
		UnitUnitIdPut,
	},

	Route{
		"EquipmentEquipmentIdDelete",
		strings.ToUpper("Delete"),
		"/equipment/{equipmentId}",
		EquipmentEquipmentIdDelete,
	},

	Route{
		"EquipmentEquipmentIdGet",
		strings.ToUpper("Get"),
		"/equipment/{equipmentId}",
		EquipmentEquipmentIdGet,
	},

	Route{
		"EquipmentEquipmentIdPut",
		strings.ToUpper("Put"),
		"/equipment/{equipmentId}",
		EquipmentEquipmentIdPut,
	},

	Route{
		"EquipmentGet",
		strings.ToUpper("Get"),
		"/equipment",
		EquipmentGet,
	},

	Route{
		"EquipmentPost",
		strings.ToUpper("Post"),
		"/equipment",
		EquipmentPost,
	},
}
